---
- hosts: all
  tasks:
    - name: install apache2
      package:
        name: apache2
        state: installed
    - name: configure
      shell: "echo Hello Lumen guys , raman khanna this side  !! > /var/www/html/index.html"
    - name: start service
      service:
        name: apache2
        state: started
    - name: add user
      user:
        name: raman
        state: absent
